trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(PipelineLevelVariable)
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob
- stage: DevDeploy
  variables:
    enviornment: Dev
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo $(environment)DeployJob
- stage: QADeploy
  variables:
    enviornment: QA
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo $(enviornment)DeployJob
- stage: ProdDeploy
  variables:
    enviornment: Prod
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo $(environment)DeployJob